Caso de uso Manter Instituição implementado
marcosdosea/QueroJobs pull request #210
Opened 2022-10-19 03:27 UTC by XxthiagoboyXx

Caso de uso implementado. Ele é acessado através do painel Admin. Resolve #184.

2022-10-19 03:29 UTC, XxthiagoboyXx commented
Favor revisar.

2022-10-19 23:30 UTC, Ericles-Porty requested changes

2022-10-19 23:30 UTC, Ericles-Porty commented on Codigo/QueroJobs/Core/Services/IInstitutionService.cs
> +    Task UpdateInstitutionNameById(int id, string institutionName);
Essa UpdateInstitutionNameById é desnecessária, já que a edit faz exatamente isso

2022-10-19 23:30 UTC, Ericles-Porty commented on Codigo/QueroJobs/QueroJobsWEB/Controllers/AdminController.cs
> +using Services;
Essa importação aparentemente é desnecessária.

2022-10-19 23:30 UTC, Ericles-Porty commented on Codigo/QueroJobs/QueroJobsWEB/Controllers/InstitutionController.cs
> +public class InstitutionController : Controller
Instituição não necessite de controladores, apenas os admin podem alterar os valores visualmente, e, as outras funcionalidades de instituição são extraídas da service.

2022-10-19 23:43 UTC, Ericles-Porty commented on Codigo/QueroJobs/Services/InstitutionService.cs
> +    public async Task UpdateInstitutionNameById(int id, string institutionName)
Lembrar de remover esse método também

2022-10-20 00:22 UTC, Ericles-Porty approved these changes
Fabuloso!

2022-10-20 00:22 UTC, merged