ADD:: Vacancy tests
marcosdosea/QueroJobs pull request #216
Opened 2022-10-21 02:18 UTC by joannestephany

se alguem puder me ajudar, agradeço

2022-10-22 00:02 UTC, joannestephany commented
Olá, alguém poderia revisar? @MariaMilena @Ericles-Porty @Kendy619 @XxthiagoboyXx

2022-10-22 00:31 UTC, Kendy619 requested changes
![image](https://user-images.githubusercontent.com/68467958/197308090-f578e950-0684-4ebc-91b0-bb2a19d2827c.png)

Joanne, alguns testes falharam como mostra na imagem acima.  Poderia ajustar na VacancyControllerTest o DetailsTest e EditTest_Get?

Aproveitando, em VacancyServiceTest também houve uma falha, poderia checar o EditTest e corrigir o erro?

2022-10-22 01:13 UTC, joannestephany commented
OBRIGADA FOI SUPER AUTO EXPLICATIVO

2022-10-22 01:13 UTC, joannestephany commented
A CAIXA ALTA É PQ ESTOU ESTUDANDO BANCO

2022-10-22 01:22 UTC, joannestephany commented
@Kendy619 CORRIJA POR FAVOR

2022-10-22 01:50 UTC, joannestephany commented
@Ericles-Porty EU SEI QUE VC TA ACORDADO, REVISA POR FAVOR

2022-10-22 01:58 UTC, Kendy619 approved these changes
Perfeito, caso de teste implementado!

2022-10-22 01:58 UTC, merged

2022-10-22 01:58 UTC, joannestephany commented
OBRIGADA

2022-11-24 03:01 UTC, joannestephany commented
Gente, eu nao vi em qual versao ficou esse PR, alguem sabe me dizer?